### ISSUE TITLE
Add attendance manager

### ISSUE THREAD

**Issue by pwnfoo** [niranjan94/amrita-info-desk#2]
# What?

It'll be totally cool to have an attendance manager within the app to assist people 'bunk' the class.
# How?

I guess the statistics for this has to be crowd-sourced / drawn from somewhere. If we can have the mappings of course-codes : credits, we can roughly approximate the number of hours one can bunk without falling into the _red_ category. What I suggest is a combination of the mapping and the current standings of the attendance and suggest if the user can bunk or not. (Recommendation Systems? Woot Woot.)

**Comment by rajkumaar23** [comment]
@sachinkamath What you were looking for is available [here](http://bit.ly/amritarepo) :nerd_face:
