### ISSUE TITLE
Query in gpmsClient.java

### ISSUE THREAD

**Issue by vaidhyesh1** [niranjan94/amrita-info-desk#7]
When i was looking at gpmsClient.java in (/gpms/client) ,I saw this line
"public String PROXY_URL = "https://anokha.amrita.edu/glype/browse.php?b=4";".(Line 37)
When i went to that link,there was glype running inside anokha.amrita.edu . Is this legal? 
P.S : I'm new at this ,so correct me if i am wrong!!

**Comment by niranjan94** [comment]
@drunkskunk I cannot comment on the legality of that :sweat_smile: .. But it got the job done. I'll anyway be removing glype now and replacing it with a more secure alternative. (which would allow access only to GPMS)

**Comment by vaidhyesh1** [comment]
But using anokha.amrita.edu is trickery, isn't it??That's my point. There must be some legal way!

**Comment by niranjan94** [comment]
Yep. It is trickery. Can't deny that :smiling_imp:

**Comment by pwnfoo** [comment]
Well, if it gets the job done, isn't it arguably a ['hack'](http://www.catb.org/jargon/html/meaning-of-hack.html) ;)

**Comment by pwnfoo** [comment]
Closing this for now. @drunkskunk , please open a new issue for enhancing the GPMS feature :)

**Comment by pwnfoo** [comment]
@drunkskunk We have moved away from glype. Good luck figuring out the mechanism now ;)

**Comment by vaidhyesh1** [comment]
I noticed that!! xD
